quarkus.application.name=NextCart BackOffice
quarkus.application.version=1.0.0

quarkus.http.port=8080
quarkus.http.cors=true

quarkus.http.cors.origins=*

quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH

quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,origin,access-control-request-method,access-control-request-headers

quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root

quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/progetto?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true


quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQLDialect


mp.jwt.verify.publickey.location=keys/publicKey.pem
smallrye.jwt.sign.key.location=keys/privateKey.pem
mp.jwt.verify.issuer=http://localhost:8080/issuer # O il tuo valore scelto


quarkus.smallrye-openapi.path=/api/v1/openapi
quarkus.swagger-ui.path=/api/v1/swagger-ui
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=NextCart BackOffice API
quarkus.smallrye-openapi.info-version=${quarkus.application.version}
quarkus.smallrye-openapi.info-description=API REST per la gestione del sistema BackOffice di NextCart.
quarkus.swagger-ui.title=NextCart BackOffice API # Titolo per la pagina HTML di Swagger UI


quarkus.log.level=INFO
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.example".level=DEBUG

quarkus.log.category."io.quarkus.vertx.http".level=DEBUG

%dev.quarkus.profile=dev
app.admin.default.email=admin@example.com
app.admin.default.password=password


quarkus.index-dependency.nextcart.group-id=it.nextre.nextcart
quarkus.index-dependency.nextcart.artifact-id=NextCartInterface